title: Multiverse by HTML5 UP
author: João Neto
email: joao@neto.pt
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

social:
  twitter: joaomlneto
  facebook: joaomlneto
  instagram: joaomlneto
  github: joaomlneto
  linkedin:

repository: https://github.com/AxelKrypton/Columbia-plots-and-alikes
pdf_dir_url: https://github.com/AxelKrypton/Columbia-plots-and-alikes/blob/main/Pdf
svg_dir_url: https://github.com/AxelKrypton/Columbia-plots-and-alikes/blob/main/Svg

# References (they require '| markdownify' to be rendered in HTML)
ref:
  - "[Alessandro Sciarra's Ph.D. thesis (2016)](https://github.com/AxelKrypton/PhD_Thesis/blob/main/Sciarra_Thesis_digital.pdf)"
  - "[Cuteri, Philipsen, Sciarra (2021)](https://arxiv.org/pdf/2107.12739.pdf)" # Cuteri, Philipsen, Sciarra paper

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-liquify
  - jekyll-seo-tag

collections:
  images:
    output: true

sass:
  sass_dir: assets/sass
  style: expanded

encoding: utf-8