title: Columbia plots and alike
author: Alessandro Sciarra
email: sciarra@itp.uni-frankfurt.de
description: >-
  A collection of QCD related sketches I did during my Ph.D. and afterwards.
  Many people asked me many times if it was possible to get the source files
  behind the PDF figures, which I then decided to make public.

social:
  github: AxelKrypton

repository: https://github.com/AxelKrypton/Columbia-plots-and-alikes
pdf_dir_url: https://github.com/AxelKrypton/Columbia-plots-and-alikes/blob/main/Pdf
svg_dir_url: https://github.com/AxelKrypton/Columbia-plots-and-alikes/blob/main/Svg

# References (they require '| markdownify' to be rendered in HTML)
ref:
  - "[Alessandro Sciarra's Ph.D. thesis (2016)](https://github.com/AxelKrypton/PhD_Thesis/blob/main/Sciarra_Thesis_digital.pdf)"
  - "[Cuteri, Philipsen, Sciarra (2021)](https://arxiv.org/pdf/2107.12739.pdf)" # Cuteri, Philipsen, Sciarra JHEP paper
  - "[Cuteri, Philipsen, Sciarra (2017)](https://arxiv.org/pdf/1711.05658.pdf)" # Cuteri, Philipsen, Sciarra PRD paper

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-liquify
  - jekyll-seo-tag

collections:
  images:
    output: true

sass:
  sass_dir: assets/sass
  style: expanded

encoding: utf-8